#!/bin/bash

if [ "$1" = "clean" ] || [ "$1" = "kc" ]; then
   CLEAN_CMD="make clean"
   CLEAN_ARG="kc"
fi

mv ~/download/kernel/* ~/download/kernel/old/

cd /home/changmin/kernel/siyah-v4/siyahkernel3
$CLEAN_CMD
./build_kernel.sh no

sleep 3
cd /home/changmin/kernel/siyah-v5/siyahkernel3
$CLEAN_CMD
./build_s2_kernel.sh no

sleep 3
mr1kernel $CLEAN_ARG

sleep 3
mr0kernel $CLEAN_ARG
