#!/bin/bash

DMD=$(date -u +%Y%m%d);cd ~/download/kernel;
scp *$DMD*.zip changmin811@frs.sourceforge.net:/home/frs/project/cm10i9100vsync/kernel/

[ "$1" != "noreadme" ] && scp ~/android/README changmin811@frs.sourceforge.net:/home/frs/project/cm10i9100vsync/
