#!/bin/bash

adb_mount_fs()
{
    local FSTYPE=$1
    local DEVICE=$2
    local MNTDIR=$3
    local ADBCMD="[ -d $MNTDIR ] && ((df|grep $MNTDIR) > /dev/null 2>&1 || mount -t $FSTYPE $DEVICE $MNTDIR)"
    # echo $ADBCMD
    adb shell su -c "$ADBCMD"
    return $?
}

adb_wipe_dalvik_cache()
{
    adb_mount_fs ext4 /dev/block/mmcblk0p7  /cache
    adb_mount_fs ext4 /dev/block/mmcblk0p10 /data
    adb shell "rm /data/dalvik-cache/*"
    adb shell "rm /cache/dalvik-cache/*"
}

get_dir()
{
    local DIR0=/sdcard/$1;
    local DIR1=/emmc/$1;
    local DIR2=/storage/sdcard1/$1;
    DIR=$(adb shell "\
		([ -d $DIR0 ] && echo -n $DIR0) || \
		([ -d $DIR1 ] && echo -n $DIR1) || \
		([ -d $DIR2 ] && echo -n $DIR2)")
    test ! -z "$DIR"
    return $?
}

get_phone()
{
    local DIR="A"
    local DIR0=/storage/sdcard0/$DIR;
    local DIR1=/storage/sdcard1/$DIR;
    local DIR2=/emmc/$DIR;
    local DIR3=/sdcard/$DIR;
    eval 'TARGET= $(\
		([ -d $DIR0 ] && echo -n $DIR0) || \
		([ -d $DIR1 ] && echo -n $DIR1) || \
		([ -d $DIR2 ] && echo -n $DIR2) || \
		([ -d $DIR3 ] && echo -n $DIR3))'
    test ! -z "$TARGET"
    return $?
}

push_file()
{
    if get_dir "Download"; then
	echo "adb push $1 $DIR"
	adb push $1 $DIR
    else
	adb_mount_fs vfat /dev/block/mmcblk0p11 /storage/sdcard0
	adb_mount_fs vfat /dev/block/mmcblk0p11 /emmc
	adb_mount_fs vfat /dev/block/mmcblk1p1 /storage/sdcard1
	adb_mount_fs vfat /dev/block/mmcblk1p1 /sdcard
	get_dir "Download" && adb push $1 $DIR
    fi
    return $?
}

update_package()
{
    get_dir "A"
    FILES=$(adb shell "cd $DIR;busybox ls -t cm*.zip")
    for FILE in $FILES; do
	ZIPFILE="--update_package=/emmc/A/$FILE"
	adb shell su -c "echo $ZIPFILE > /cache/recovery/command"
	return 0
	break
    done
    return 1
}

if [ "$(adb get-state)" != "device" ]; then
    echo "rompush failed: device not found"
    #exit 1
fi

if [ -d /cygdrive/e/download ]; then
    DOWNLOAD_PATH=/cygdrive/e/download
elif [ -d ~/download ]; then
    DOWNLOAD_PATH=~/download
fi

TEMP_FILE="$DOWNLOAD_PATH/cm-i9100-temp.zip"
[ -e "$TEMP_FILE" ] && rm "$TEMP_FILE"

if [ -e "$1" ]; then
    echo "push $1"
    cp "$1" "$TEMP_FILE"
else
    cd $DOWNLOAD_PATH
    FILES=$(ls -t [Cc][Mm]*NIGHTLY*.zip cm-*-*i9100*.zip vsync_*/cm-*-*i9100*.zip 2> /dev/null)
    for FILE in $FILES; do
	if [ -f "$FILE" ]; then
            echo "push $FILE"
	    cp $FILE $TEMP_FILE
	    break;
	fi
    done
fi

if [ -e "$TEMP_FILE" ]; then
    # 7z l $TEMP_FILE boot.img | grep -e boot.img
    # if [ -z "$1" ]; then
    # 	7z d -y $TEMP_FILE boot.img
    # 	7z l $TEMP_FILE boot.img | grep -e boot.img
    # fi
    adb root
    sleep 3
    get_dir "Download" && adb shell "rm -f $DIR/cm-*i9100-temp.zip"
    push_file $TEMP_FILE
    rm $TEMP_FILE
    echo "reboot recovery..."
    adb reboot recovery
fi
